# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Wendy Owens
email: me@wendyowensbooks.com
description: > # this means to ignore newlines until "baseurl:"
  Wendy Owens is an Indie eBook Author who has written series New Adult Romance 
  series Stubborn Love & Young Adult Fantasy Sacred Guardians saga.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wendyowensbooks.com" # the base hostname & protocol for your site
twitter_username: WendyLOwens

collections:
  books:
    output: true
    title: Books
    permalink: /books/:path/
  bookGroups:
    output: true
    title: Series
    permalink: /series/:path/
  genres:
    output: true
    title: Genre
    permalink: /genre/:path/

# Build settings
markdown: kramdown
exclude: ["_site/"]
