backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "img" # Media files will be stored in the repo under images/uploads

collections:
  - name: "books" # Used in routes, e.g., /admin/collections/blog
    label: "Books" # Used in the UI
    folder: "_books" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "book"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Genre", name: "genre", widget: "string"}
      - {label: "Cover Image", name: "cover-image", widget: "image"}
      - {label: "Series", name: "series", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Book Number", name: "bookNumber", widget: "number"}
      - {label: "Amazon Link", name: "amazonLink", widget: "string"}
      - {label: "Rating", name: "rating", widget: "number"}
      - {label: "Review Count", name: "reviewCount", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Excerpt Separator", name: "excerpt_separator", widget: "hidden", default: "<!--more-->"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "date", format: 'MMM Do YY'}